from uuid import UUID

from ..routing import Sharder, Token
from .metadata import Keyspace

class NodeShard:
    def __init__(self, host_id: UUID, shard: int | None = None) -> None: ...
    @property
    def host_id(self) -> UUID: ...
    @property
    def shard(self) -> int | None: ...
    def __repr__(self) -> str: ...

class Node:
    @property
    def host_id(self) -> UUID: ...
    @property
    def address(self) -> str: ...
    @property
    def datacenter(self) -> str | None: ...
    @property
    def rack(self) -> str | None: ...
    @property
    def node_shard(self) -> NodeShard: ...
    def sharder(self) -> Sharder | None: ...
    def is_connected(self) -> bool: ...
    def is_enabled(self) -> bool: ...
    def __repr__(self) -> str: ...

class ClusterState:
    def get_keyspace(self, keyspace: str) -> Keyspace | None: ...
    def keyspaces_iter(self) -> dict[str, Keyspace]: ...
    def get_nodes_info(self) -> list[Node]: ...
    def compute_token(self, keyspace: str, table: str, partition_key: int) -> Token: ...
    def get_token_endpoints(self, table_spec: tuple[str, str], token: Token) -> list[tuple[Node, int]]: ...
    def get_endpoints(self, table_spec: tuple[str, str], partition_key: int) -> list[Node]: ...
    def datacenter_names(self) -> list[str]: ...
    def unique_nodes_in_global_ring(self) -> list[Node]: ...
    def unique_nodes_in_datacenter_ring(self, datacenter: str) -> list[Node] | None: ...
    def ring_len(self) -> int: ...
    def __repr__(self) -> str: ...
