from __future__ import annotations

from uuid import UUID

from ..routing import ReplicaLocator, Sharder, Token
from .metadata import Keyspace

class NodeShard:
    def __init__(self, host_id: UUID, shard: int | None = None) -> None: ...
    @property
    def host_id(self) -> UUID: ...
    @property
    def shard(self) -> int | None: ...
    def __repr__(self) -> str: ...

class Node:
    @property
    def host_id(self) -> UUID: ...
    @property
    def address(self) -> str: ...
    @property
    def datacenter(self) -> str | None: ...
    @property
    def rack(self) -> str | None: ...
    @property
    def node_shard(self) -> NodeShard: ...
    def sharder(self) -> Sharder | None: ...
    def is_connected(self) -> bool: ...
    def is_enabled(self) -> bool: ...
    def __repr__(self) -> str: ...

class ClusterState:
    def get_keyspace(self, keyspace: str) -> Keyspace | None: ...
    def get_keyspaces(self) -> dict[str, Keyspace]: ...
    def get_nodes_info(self) -> list[Node]: ...
    def compute_token(self, keyspace: str, table: str, partition_key: object) -> Token: ...
    def get_token_endpoints(self, table_spec: tuple[str, str], token: Token) -> list[tuple[Node, int]]: ...
    def get_endpoints(self, table_spec: tuple[str, str], partition_key: object) -> list[Node]: ...
    def replica_locator(self) -> ReplicaLocator: ...
    def __repr__(self) -> str: ...
