from enum import IntEnum

class ColumnKind(IntEnum):
    Regular = ...
    Static = ...
    Clustering = ...
    PartitionKey = ...

class Column:
    @property
    def typ(self) -> str: ...
    @property
    def kind(self) -> ColumnKind: ...
    def __repr__(self) -> str: ...

class Table:
    @property
    def columns(self) -> dict[str, Column]: ...
    @property
    def partition_key(self) -> list[str]: ...
    @property
    def clustering_key(self) -> list[str]: ...
    @property
    def partitioner(self) -> str | None: ...
    def __repr__(self) -> str: ...

class MaterializedView:
    @property
    def base_table_name(self) -> str: ...
    @property
    def view_columns(self) -> dict[str, Column]: ...
    @property
    def view_partition_key(self) -> list[str]: ...
    @property
    def view_clustering_key(self) -> list[str]: ...
    @property
    def view_partitioner(self) -> str | None: ...
    def __repr__(self) -> str: ...

class UserDefinedType:
    @property
    def name(self) -> str: ...
    @property
    def keyspace(self) -> str: ...
    def __repr__(self) -> str: ...

class Keyspace:
    @property
    def strategy_name(self) -> str: ...
    @property
    def strategy_replication_factor(self) -> int | None: ...
    @property
    def strategy_datacenter_repfactors(self) -> dict[str, int] | None: ...
    @property
    def strategy_other_name(self) -> str | None: ...
    @property
    def strategy_other_data(self) -> dict[str, str] | None: ...
    @property
    def tables(self) -> dict[str, Table]: ...
    @property
    def views(self) -> dict[str, MaterializedView]: ...
    @property
    def user_defined_types(self) -> dict[str, UserDefinedType]: ...
    def __repr__(self) -> str: ...
