from __future__ import annotations

from enum import IntEnum

class StrategyKind(IntEnum):
    Simple = ...
    NetworkTopology = ...
    Local = ...
    Other = ...

class Strategy:
    @property
    def kind(self) -> StrategyKind: ...
    @property
    def replication_factor(self) -> int | None: ...
    @property
    def datacenter_repfactors(self) -> dict[str, int] | None: ...
    @property
    def other_name(self) -> str | None: ...
    @property
    def other_data(self) -> dict[str, str] | None: ...
    def __repr__(self) -> str: ...

class ColumnKind(IntEnum):
    Regular = ...
    Static = ...
    Clustering = ...
    PartitionKey = ...

class Column:
    @property
    def typ(self) -> str: ...
    @property
    def kind(self) -> ColumnKind: ...
    def __repr__(self) -> str: ...

class Table:
    @property
    def columns(self) -> dict[str, Column]: ...
    @property
    def partition_key(self) -> list[str]: ...
    @property
    def clustering_key(self) -> list[str]: ...
    @property
    def partitioner(self) -> str | None: ...
    def __repr__(self) -> str: ...

class MaterializedView:
    @property
    def base_table_name(self) -> str: ...
    @property
    def view_columns(self) -> dict[str, Column]: ...
    @property
    def view_partition_key(self) -> list[str]: ...
    @property
    def view_clustering_key(self) -> list[str]: ...
    @property
    def view_partitioner(self) -> str | None: ...
    def __repr__(self) -> str: ...

class Keyspace:
    @property
    def strategy(self) -> Strategy: ...
    @property
    def tables(self) -> dict[str, Table]: ...
    @property
    def views(self) -> dict[str, MaterializedView]: ...
    def __repr__(self) -> str: ...
