from __future__ import annotations

from ._rust.errors import (  # pyright: ignore[reportMissingModuleSource]
    BatchError,
    ClusterStateTokenError,
    DecodeFailedError,
    DeserializationError,
    ExecuteError,
    PrepareError,
    PyConversionFailedError,
    PySerializationFailedError,
    RowIterationError,
    SchemaAgreementError,
    ScyllaError,
    SerializationError,
    SerializeFailedError,
    SessionConfigError,
    SessionConnectionError,
    StatementConfigError,
    StatementConversionError,
    TypeMismatchSerializationError,
    UnsupportedTypeDeserializationError,
    UnsupportedTypeSerializationError,
    ValueOverflowSerializationError,
)

__all__ = [
    "ScyllaError",
    "RowIterationError",
    "DeserializationError",
    "UnsupportedTypeDeserializationError",
    "DecodeFailedError",
    "PyConversionFailedError",
    "SessionConnectionError",
    "SessionConfigError",
    "StatementConversionError",
    "PrepareError",
    "ExecuteError",
    "SchemaAgreementError",
    "StatementConfigError",
    "BatchError",
    "SerializationError",
    "UnsupportedTypeSerializationError",
    "TypeMismatchSerializationError",
    "ValueOverflowSerializationError",
    "SerializeFailedError",
    "PySerializationFailedError",
    "ClusterStateTokenError",
]
