from __future__ import annotations
from ._rust.errors import (  # pyright: ignore[reportMissingModuleSource]
    ScyllaError,
    RowIterationError,
    DeserializationError,
    UnsupportedTypeDeserializationError,
    DecodeFailedError,
    PyConversionFailedError,
    SessionConnectionError,
    SessionConfigError,
    TlsError,
    StatementConversionError,
    PrepareError,
    ExecuteError,
    SchemaAgreementError,
    StatementConfigError,
    BatchError,
    SerializationError,
    UnsupportedTypeSerializationError,
    TypeMismatchSerializationError,
    ValueOverflowSerializationError,
    SerializeFailedError,
    PySerializationFailedError,
)

__all__ = [
    "ScyllaError",
    "RowIterationError",
    "DeserializationError",
    "UnsupportedTypeDeserializationError",
    "DecodeFailedError",
    "PyConversionFailedError",
    "SessionConnectionError",
    "SessionConfigError",
    "TlsError",
    "StatementConversionError",
    "PrepareError",
    "ExecuteError",
    "SchemaAgreementError",
    "StatementConfigError",
    "BatchError",
    "SerializationError",
    "UnsupportedTypeSerializationError",
    "TypeMismatchSerializationError",
    "ValueOverflowSerializationError",
    "SerializeFailedError",
    "PySerializationFailedError",
]
