from enum import IntEnum
from typing import Any, Sequence

from .enums import Consistency, SerialConsistency
from .execution_profile import ExecutionProfile
from .statement import PreparedStatement, Statement
from .types import UnsetType

class BatchType(IntEnum):
    Logged = ...
    Unlogged = ...
    Counter = ...

class Batch:
    """
    CQL batch statement with immutable configuration.

    Any mix of prepared and unprepared statements is allowed.
    For maximum performance, it is recommended to use prepared statements
    whenever possible.

    All `with_*` and `without_*` methods create and return a new instance of
    Batch with the modified configuration. The original instance
    (`self`) retains its old configuration and remains unchanged.
    """
    def __init__(self, batch_type: BatchType = BatchType.Logged) -> None: ...
    def add(self, statement: str | Statement | PreparedStatement, values: Any | None = None) -> None: ...
    def add_all(self, items: Sequence[tuple[str | Statement | PreparedStatement, Any | None]]) -> None: ...
    @property
    def type(self) -> BatchType: ...
    def with_execution_profile(self, profile: ExecutionProfile) -> Batch: ...
    def without_execution_profile(self) -> Batch: ...
    @property
    def execution_profile(self) -> ExecutionProfile | None: ...
    def with_consistency(self, c: Consistency) -> Batch: ...
    def without_consistency(self) -> Batch: ...
    @property
    def consistency(self) -> Consistency | None: ...
    def with_serial_consistency(self, sc: SerialConsistency | None) -> Batch: ...
    def without_serial_consistency(self) -> Batch: ...
    @property
    def serial_consistency(self) -> SerialConsistency | None | UnsetType: ...
    def with_request_timeout(self, timeout: float | None) -> Batch: ...
    def without_request_timeout(self) -> Batch: ...
    @property
    def request_timeout(self) -> float | None | UnsetType: ...
