# python/scylla/_rust/errors.pyi

class ScyllaError(Exception): ...
class ExecutionError(ScyllaError): ...
class BadQueryError(ExecutionError): ...
class RuntimeError(ExecutionError): ...
class ConnectionError(ExecutionError): ...
class DeserializationError(ScyllaError): ...
class UnsupportedTypeError(DeserializationError): ...
class DecodeFailedError(DeserializationError): ...
class PyConversionFailedError(DeserializationError): ...
class InternalError(DeserializationError): ...
