from __future__ import annotations

class ScyllaError(Exception): ...
class ConnectionError(ScyllaError): ...
class SessionConfigError(ScyllaError): ...
class StatementConversionError(ScyllaError): ...
class PrepareError(ScyllaError): ...
class ExecuteError(ScyllaError): ...
class SchemaAgreementError(ScyllaError): ...
class StatementConfigError(ScyllaError): ...
