from __future__ import annotations

class ScyllaError(Exception): ...
class RowIterationError(ScyllaError): ...

class DeserializationError(ScyllaError):
    column_name: str | None
    column_index: int | None
    inner_path: list[str] | None

class UnsupportedTypeDeserializationError(DeserializationError): ...
class DecodeFailedError(DeserializationError): ...
class PyConversionFailedError(DeserializationError): ...
class ConnectionError(ScyllaError): ...
class SessionConfigError(ScyllaError): ...
class StatementConversionError(ScyllaError): ...
class PrepareError(ScyllaError): ...
class ExecuteError(ScyllaError): ...
class SchemaAgreementError(ScyllaError): ...
class StatementConfigError(ScyllaError): ...
class BatchError(ScyllaError): ...

class SerializationError(ScyllaError):
    parameter: str | int | None

class UnsupportedTypeSerializationError(SerializationError): ...
class TypeMismatchSerializationError(SerializationError): ...
class ValueOverflowSerializationError(SerializationError): ...
class SerializeFailedError(SerializationError): ...
class PySerializationFailedError(SerializationError): ...
