from .enums import Consistency, SerialConsistency

class ExecutionProfile:
    def __init__(
        self,
        timeout: float | None = None,
        consistency: Consistency | None = None,
        serial_consistency: SerialConsistency | None = None,
    ) -> None: ...
    def get_request_timeout(self) -> float | None: ...
    def get_consistency(self) -> Consistency: ...
    def get_serial_consistency(self) -> SerialConsistency: ...
