from .enums import Consistency, SerialConsistency

class ExecutionProfile:
    def __init__(
        self,
        timeout: float | None = 30.0,
        consistency: Consistency = Consistency.LocalQuorum,
        serial_consistency: SerialConsistency | None = SerialConsistency.LocalSerial,
    ) -> None: ...
    def get_request_timeout(self) -> float | None: ...
    def get_consistency(self) -> Consistency: ...
    def get_serial_consistency(self) -> SerialConsistency | None: ...
