from .enums import Consistency, SerialConsistency
from .policies.load_balancing import LoadBalancingPolicy

class ExecutionProfile:
    def __init__(
        self,
        timeout: float | None = 30.0,
        consistency: Consistency = Consistency.LocalQuorum,
        serial_consistency: SerialConsistency | None = SerialConsistency.LocalSerial,
        policy: LoadBalancingPolicy | None = None,
    ) -> None: ...
    def get_request_timeout(self) -> float | None: ...
    def get_consistency(self) -> Consistency: ...
    def get_serial_consistency(self) -> SerialConsistency | None: ...
    def get_load_balancing_policy(self) -> LoadBalancingPolicy | None: ...
