from __future__ import annotations

from typing import Iterator, TypeAlias

from .cluster import Node
from .cluster.metadata import Strategy

Shard: TypeAlias = int

class Token:
    def __init__(self, value: int) -> None: ...
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

class Sharder:
    @property
    def nr_shards(self) -> int: ...
    @property
    def msb_ignore(self) -> int: ...
    def shard_of(self, token: Token) -> Shard: ...
    def shard_of_source_port(self, source_port: int) -> Shard: ...
    def draw_source_port_for_shard(self, shard: Shard) -> int: ...
    def iter_source_ports_for_shard(self, shard: Shard) -> Iterator[int]: ...

class ReplicaSetIterator:
    def __iter__(self) -> ReplicaSetIterator: ...
    def __next__(self) -> tuple[Node, Shard]: ...

class ReplicaSet:
    def __len__(self) -> int: ...
    def is_empty(self) -> bool: ...
    def to_list(self) -> list[tuple[Node, Shard]]: ...
    def __iter__(self) -> ReplicaSetIterator: ...
    def __repr__(self) -> str: ...

class ReplicaLocator:
    def replicas_for_token(
        self,
        token: Token,
        strategy: Strategy,
        datacenter: str | None,
        keyspace: str,
        table: str,
    ) -> ReplicaSet: ...
    def unique_nodes_in_global_ring(self) -> list[Node]: ...
    def unique_nodes_in_datacenter_ring(self, datacenter: str) -> list[Node] | None: ...
    def datacenter_names(self) -> list[str]: ...
    def ring_len(self) -> int: ...
    def __repr__(self) -> str: ...
