from typing import TypeAlias

Shard: TypeAlias = int

class Token:
    def __init__(self, value: int) -> None: ...
    def value(self) -> int: ...

class Sharder:
    @property
    def nr_shards(self) -> int: ...
    @property
    def msb_ignore(self) -> int: ...
    def shard_of(self, token: Token) -> Shard: ...
    def shard_of_source_port(self, source_port: int) -> Shard: ...
    def draw_source_port_for_shard(self, shard: Shard) -> int: ...
    def iter_source_ports_for_shard(self, shard: Shard) -> list[int]: ...
