from .statement import PreparedStatement

class Session:
    async def execute(self, request: PreparedStatement | str) -> RequestResult: ...
    async def prepare(self, statement: str) -> PreparedStatement: ...

class RequestResult:
    def __str__(self) -> str: ...
