from .enums import Consistency, SerialConsistency
from .execution_profile import ExecutionProfile

class PreparedStatement:
    def set_execution_profile(self, profile: ExecutionProfile) -> PreparedStatement: ...
    def unset_execution_profile(self) -> PreparedStatement: ...
    def get_execution_profile(self) -> ExecutionProfile | None: ...
    def set_consistency(self, c: Consistency) -> PreparedStatement: ...
    def unset_consistency(self) -> PreparedStatement: ...
    def get_consistency(self) -> Consistency | None: ...
    def set_serial_consistency(self, sc: SerialConsistency) -> PreparedStatement: ...
    def unset_serial_consistency(self) -> PreparedStatement: ...
    def get_serial_consistency(self) -> SerialConsistency | None: ...
    def set_request_timeout(self, timeout: float) -> PreparedStatement: ...
    def unset_request_timeout(self) -> PreparedStatement: ...
    def get_request_timeout(self) -> float | None: ...
