from .enums import Consistency, SerialConsistency
from .execution_profile import ExecutionProfile
from .types import UnsetType

class PreparedStatement:
    """
    A prepared statement with immutable configuration.

    All `with_*` and `without_*` methods create and return a new instance of
    PreparedStatement with the modified configuration. The original instance
    (`self`) retains its old configuration and remains unchanged.
    """
    def with_execution_profile(self, profile: ExecutionProfile) -> PreparedStatement: ...
    def without_execution_profile(self) -> PreparedStatement: ...
    def get_execution_profile(self) -> ExecutionProfile | None: ...
    def with_consistency(self, c: Consistency) -> PreparedStatement: ...
    def without_consistency(self) -> PreparedStatement: ...
    def get_consistency(self) -> Consistency | None: ...
    def with_serial_consistency(self, sc: SerialConsistency | None) -> PreparedStatement: ...
    def without_serial_consistency(self) -> PreparedStatement: ...
    def get_serial_consistency(self) -> SerialConsistency | None | UnsetType: ...
    def with_request_timeout(self, timeout: float | None) -> PreparedStatement: ...
    def without_request_timeout(self) -> PreparedStatement: ...
    def get_request_timeout(self) -> float | None | UnsetType: ...
