from typing import Any

from .statements import PyPreparedStatement

class PyCellOverFlowError(Exception): ...

class PyRowSerializationContext:
    @staticmethod
    def from_prepared(
        prepared_statement: PyPreparedStatement,
    ) -> PyRowSerializationContext: ...
    def column_count(self) -> int: ...
    def get_columns(self) -> list[Any]: ...

class SerializationBuffer:
    def __init__(self) -> None: ...
    def len(self) -> int: ...
    def set_element_count(self, count: int) -> None: ...

class PyCellWriter:
    def __init__(self, buffer: SerializationBuffer) -> None: ...
    def set_null(self) -> None: ...
    def set_unset(self) -> None: ...
    def set_value(self, value: bytes) -> None: ...
    def create_value_builder(self) -> PyCellValueBuilder: ...
    @staticmethod
    def new_without_size(buffer: SerializationBuffer) -> PyCellWriter: ...

class PyRowWriter:
    def __init__(self, buffer: SerializationBuffer) -> None: ...
    def make_cell_writer(self) -> PyCellWriter: ...
    def value_count(self) -> int: ...

class PyCellValueBuilder:
    def append_bytes(self, bytes: bytes) -> None: ...
    def make_sub_writer(self) -> PyCellWriter: ...
    def make_sub_writer_without_size(self) -> PyCellWriter: ...
    def finish(self) -> None: ...
